apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubernetes-assignment-volume
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: kubernetes-storage-disk
    fsType: ext4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubernetes-assignment-pvc
spec:
  selector:
    matchLabels:
      name: kubernetes-assignment-volume
  volumeName: kubernetes-assignment-volume 
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi